// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlboemuqmuqdzijezuzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsYm9lbXVxbXVxZHppamV6dXpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0MDU2NzksImV4cCI6MjA1MDk4MTY3OX0.qB6MbmNCA86wZsn_HkdQJTErb-I0H8HbwtxswbJXKBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);